# Generated by Django 5.0.6 on 2024-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_customers_cust_id_alter_customers_adhaar_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AlterField(
            model_name='customers',
            name='cust_id',
            field=models.AutoField(default=8000, primary_key=True, serialize=False, unique=True),
        ),
    ]
